# Generated by Django 3.0.3 on 2022-12-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attraction',
        ),
        migrations.AddField(
            model_name='comment',
            name='attractionpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travel.AttractionPost'),
        ),
    ]
