# Generated by Django 3.0.3 on 2023-01-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractionpost',
            options={'ordering': ['-created_at']},
        ),
    ]
