# Generated by Django 3.0.3 on 2022-12-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='attractionpost',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
