# Generated by Django 3.0.3 on 2023-01-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20230105_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='social_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
    ]
