# Generated by Django 3.0.3 on 2022-12-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20221214_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractionpost',
            old_name='user',
            new_name='CustomUser',
        ),
    ]
