# Generated by Django 3.0.3 on 2022-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20221219_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpost',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
