# Generated by Django 3.0.3 on 2022-12-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20221219_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimage'),
        ),
    ]
