# Generated by Django 3.0.3 on 2022-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20221229_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
