# Generated by Django 3.0.3 on 2022-12-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20221214_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionpost',
            name='tags',
        ),
    ]
