# Generated by Django 3.0.3 on 2022-12-14 19:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('travel', '0003_remove_attractionpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
