# Generated by Django 3.0.3 on 2023-01-02 19:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_attractionpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpost',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
