# Generated by Django 3.0.3 on 2023-01-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20230102_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='attractionpost',
            new_name='attraction',
        ),
    ]
