# Generated by Django 3.0.3 on 2023-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20230105_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='attraction_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/attractions'),
        ),
    ]
