# Generated by Django 3.0.3 on 2023-01-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20230102_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='continent',
            field=models.CharField(choices=[('EUROPE', 'EUROPE'), ('ASIA', 'ASIA'), ('AFRICA', 'AFRICA'), ('AUSTRALIA', 'AUSTRALIA'), ('NORTH AMERICA', 'NORTH AMERICA'), ('SOUTH AMERICA', 'SOUTH AMERICA'), ('ANTARCTICA', 'ANTARCTICA')], default='NONE', max_length=50),
        ),
    ]
