# Generated by Django 3.0.3 on 2023-01-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20230102_2038'),
        ('travel', '0005_attractionpost_continent'),
    ]

    operations = [
    ]
