# Generated by Django 3.0.3 on 2023-01-09 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_attractionpost_attraction_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpost',
            name='interest_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
