# Generated by Django 3.0.3 on 2023-01-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_attractionpost_attraction_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionpost',
            name='attraction_pic',
        ),
        migrations.AddField(
            model_name='attractionpost',
            name='attraction_pic_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
