# Generated by Django 3.0.3 on 2023-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_merge_20230102_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
