# Generated by Django 3.0.3 on 2023-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20230108_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpost',
            name='attraction_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/attractions'),
        ),
    ]
