# Generated by Django 3.0.3 on 2023-01-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20230108_2113'),
        ('travel', '0006_auto_20230109_1642'),
    ]

    operations = [
    ]
