# Generated by Django 3.0.3 on 2023-01-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20230109_1913'),
        ('travel', '0010_merge_20230109_1941'),
    ]

    operations = [
    ]
