# Generated by Django 3.0.3 on 2023-01-09 20:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_merge_20230109_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
